Fix/secuirty issues
sovware/directorist pull request #1030
Opened 2022-07-19 09:55 UTC by syedgalib

2022-07-20 04:55 UTC, obiPlabon requested changes
There are more issues similar to the feedback I shared. Please check them

2022-07-20 10:10 UTC, kowsar89 requested changes
```
FILE: /media/k/SSD/htdocs/wptest/wp-content/plugins/directorist/includes/asset-loader/helper.php


FILE: /media/k/SSD/htdocs/wptest/wp-content/plugins/directorist/includes/asset-loader/init.php
 178 | ERROR | Resource version not set in call to wp_enqueue_script(). This means new versions of the script will not always be loaded due to browser caching.
 179 | ERROR | Resource version not set in call to wp_enqueue_script(). This means new versions of the script will not always be loaded due to browser caching.
 275 | ERROR | Resource version not set in call to wp_enqueue_script(). This means new versions of the script will not always be loaded due to browser caching.
 276 | ERROR | Resource version not set in call to wp_enqueue_script(). This means new versions of the script will not always be loaded due to browser caching.


FILE: /media/k/SSD/htdocs/wptest/wp-content/plugins/directorist/includes/asset-loader/localized_data.php
 118 | ERROR | [ ] Detected usage of a possibly undefined superglobal array index: $_SERVER['HTTP_HOST']. Use isset() or empty() to check the index exists before using it
 118 | ERROR | [ ] $_SERVER data not unslashed before sanitization. Use wp_unslash() or similar
 118 | ERROR | [ ] Detected usage of a possibly undefined superglobal array index: $_SERVER['REQUEST_URI']. Use isset() or empty() to check the index exists before using it
 118 | ERROR | [ ] $_SERVER data not unslashed before sanitization. Use wp_unslash() or similar
 119 | ERROR | [ ] $_GET data not unslashed before sanitization. Use wp_unslash() or similar
 144 | ERROR | [ ] A gettext call containing placeholders was found, but was not accompanied by a "translators:" comment on the line above to clarify the meaning of the placeholders.
 234 | ERROR | [ ] $_GET data not unslashed before sanitization. Use wp_unslash() or similar
 240 | ERROR | [ ] $_GET data not unslashed before sanitization. Use wp_unslash() or similar


FILE: /media/k/SSD/htdocs/wptest/wp-content/plugins/directorist/includes/asset-loader/scripts.php


FILE: /media/k/SSD/htdocs/wptest/wp-content/plugins/directorist/includes/data-store/class-atbdp-listing-store.php
 118 | ERROR | [ ] $_GET data not unslashed before sanitization. Use wp_unslash() or similar
 119 | ERROR | [ ] $_GET data not unslashed before sanitization. Use wp_unslash() or similar


FILE: /media/k/SSD/htdocs/wptest/wp-content/plugins/directorist/includes/data-store/class-atbdp-terms-store.php


FILE: /media/k/SSD/htdocs/wptest/wp-content/plugins/directorist/includes/hooks/class-atbdp-hooks.php


FILE: /media/k/SSD/htdocs/wptest/wp-content/plugins/directorist/includes/hooks/class-atbdp-title-update.php


FILE: /media/k/SSD/htdocs/wptest/wp-content/plugins/directorist/includes/modules/appsero/src/Client.php
 255 | ERROR | [ ] Detected usage of a possibly undefined superglobal array index: $_SERVER['REMOTE_ADDR']. Use isset() or empty() to check the index exists before using it
 270 | ERROR | [ ] Method name "Client::__trans" is invalid; only PHP magic methods should be prefixed with a double underscore


FILE: /media/k/SSD/htdocs/wptest/wp-content/plugins/directorist/includes/modules/appsero/src/Insights.php
   50 | ERROR | [ ] Missing parameter name
  359 | ERROR | [ ] Detected usage of a possibly undefined superglobal array index: $_SERVER['HTTP_HOST']. Use isset() or empty() to check the index exists before using it
  359 | ERROR | [ ] $_SERVER data not unslashed before sanitization. Use wp_unslash() or similar
  359 | ERROR | [ ] Detected usage of a non-sanitized input variable: $_SERVER['HTTP_HOST']
  360 | ERROR | [ ] Detected usage of a possibly undefined superglobal array index: $_SERVER['SERVER_ADDR']. Use isset() or empty() to check the index exists before using it
  360 | ERROR | [ ] $_SERVER data not unslashed before sanitization. Use wp_unslash() or similar
  360 | ERROR | [ ] Detected usage of a non-sanitized input variable: $_SERVER['SERVER_ADDR']
  437 | ERROR | [ ] All output should be run through an escaping function (see the Security sections in the WordPress Developer Handbooks), found '$this'.
  438 | ERROR | [ ] All output should be run through an escaping function (see the Security sections in the WordPress Developer Handbooks), found '$this'.
  509 | ERROR | [ ] Use placeholders and $wpdb->prepare(); found interpolated variable $post_type at "SELECT count(ID) FROM $wpdb->posts WHERE post_type = '$post_type' and post_status =
  523 | ERROR | [ ] $_SERVER data not unslashed before sanitization. Use wp_unslash() or similar
  523 | ERROR | [ ] Detected usage of a non-sanitized input variable: $_SERVER['SERVER_SOFTWARE']
  770 | ERROR | [ ] Processing form data without nonce verification.
  775 | ERROR | [ ] Processing form data without nonce verification.
  775 | ERROR | [ ] $_POST data not unslashed before sanitization. Use wp_unslash() or similar
  776 | ERROR | [ ] $_REQUEST data not unslashed before sanitization. Use wp_unslash() or similar
  776 | ERROR | [ ] Detected usage of a non-sanitized input variable: $_REQUEST['reason_info']
  835 | ERROR | [ ] All output should be run through an escaping function (see the Security sections in the WordPress Developer Handbooks), found '$this'.


FILE: /media/k/SSD/htdocs/wptest/wp-content/plugins/directorist/includes/modules/appsero/src/License.php
  64 | ERROR | [ ] Missing parameter name
 144 | ERROR | [ ] Missing parameter name
 145 | ERROR | [ ] Missing parameter name
 233 | ERROR | [ ] Processing form data without nonce verification.
 234 | ERROR | [ ] Processing form data without nonce verification.
 255 | ERROR | [ ] All output should be run through an escaping function (see the Security sections in the WordPress Developer Handbooks), found '$this'.
 255 | ERROR | [ ] All output should be run through an escaping function (see the Security sections in the WordPress Developer Handbooks), found '$this'.
 259 | ERROR | [ ] All output should be run through an escaping function (see the Security sections in the WordPress Developer Handbooks), found 'wp_create_nonce'.
 507 | ERROR | [ ] All output should be run through an escaping function (see the Security sections in the WordPress Developer Handbooks), found '$this'.
 507 | ERROR | [ ] All output should be run through an escaping function (see the Security sections in the WordPress Developer Handbooks), found '$license['remaining']'.
 507 | ERROR | [ ] All output should be run through an escaping function (see the Security sections in the WordPress Developer Handbooks), found '$license['activation_limit']'.
 716 | ERROR | [ ] Detected usage of a possibly undefined superglobal array index: $_SERVER['SCRIPT_NAME']. Use isset() or empty() to check the index exists before using it
 716 | ERROR | [ ] $_SERVER data not unslashed before sanitization. Use wp_unslash() or similar
 716 | ERROR | [ ] Detected usage of a non-sanitized input variable: $_SERVER['SCRIPT_NAME']
 719 | ERROR | [ ] All output should be run through an escaping function (see the Security sections in the WordPress Developer Handbooks), found 'apply_filters'.
 725 | ERROR | [ ] Missing parameter name


FILE: /media/k/SSD/htdocs/wptest/wp-content/plugins/directorist/includes/modules/appsero/src/Updater.php
  21 | ERROR | [ ] Missing parameter name


FILE: /media/k/SSD/htdocs/wptest/wp-content/plugins/directorist/includes/modules/background-process/wp-async-request.php


FILE: /media/k/SSD/htdocs/wptest/wp-content/plugins/directorist/includes/modules/background-process/wp-background-process.php
  69 | ERROR | [ ] Function return type is void, but function contains return statement
 425 | ERROR | [ ] A gettext call containing placeholders was found, but was not accompanied by a "translators:" comment on the line above to clarify the meaning of the placeholders.


FILE: /media/k/SSD/htdocs/wptest/wp-content/plugins/directorist/includes/modules/multi-directory-setup/class-multi-directory-manager.php
  336 | ERROR | [ ] Processing form data without nonce [...]

2022-07-20 10:44 UTC, kowsar89 commented
35 nonce issues detected in wpcs

wpcs output:
```

FILE: /media/k/SSD/htdocs/wptest/wp-content/plugins/directorist/includes/asset-loader/helper.php
 172 | WARNING | [ ] Processing form data without nonce verification.
 180 | WARNING | [ ] Processing form data without nonce verification.
 180 | WARNING | [ ] Processing form data without nonce verification.
 180 | WARNING | [ ] Processing form data without nonce verification.
 206 | WARNING | [ ] Processing form data without nonce verification.
 206 | WARNING | [ ] Processing form data without nonce verification.
FILE: /media/k/SSD/htdocs/wptest/wp-content/plugins/directorist/includes/asset-loader/init.php
FILE: /media/k/SSD/htdocs/wptest/wp-content/plugins/directorist/includes/asset-loader/localized_data.php
 119 | WARNING | [ ] Processing form data without nonce verification.
 119 | WARNING | [ ] Processing form data without nonce verification.
 234 | WARNING | [ ] Processing form data without nonce verification.
 234 | WARNING | [ ] Processing form data without nonce verification.
 240 | WARNING | [ ] Processing form data without nonce verification.
 240 | WARNING | [ ] Processing form data without nonce verification.
FILE: /media/k/SSD/htdocs/wptest/wp-content/plugins/directorist/includes/asset-loader/scripts.php
FILE: /media/k/SSD/htdocs/wptest/wp-content/plugins/directorist/includes/data-store/class-atbdp-listing-store.php
 118 | WARNING | [ ] Processing form data without nonce verification.
 118 | WARNING | [ ] Processing form data without nonce verification.
 119 | WARNING | [ ] Processing form data without nonce verification.
 119 | WARNING | [ ] Processing form data without nonce verification.
FILE: /media/k/SSD/htdocs/wptest/wp-content/plugins/directorist/includes/data-store/class-atbdp-terms-store.php
FILE: /media/k/SSD/htdocs/wptest/wp-content/plugins/directorist/includes/hooks/class-atbdp-hooks.php
FILE: /media/k/SSD/htdocs/wptest/wp-content/plugins/directorist/includes/hooks/class-atbdp-title-update.php
FILE: /media/k/SSD/htdocs/wptest/wp-content/plugins/directorist/includes/modules/appsero/src/Client.php
FILE: /media/k/SSD/htdocs/wptest/wp-content/plugins/directorist/includes/modules/appsero/src/Insights.php
  456 | WARNING | [ ] Processing form data without nonce verification.
  456 | WARNING | [ ] Processing form data without nonce verification.
  463 | WARNING | [ ] Processing form data without nonce verification.
  463 | WARNING | [ ] Processing form data without nonce verification.
  770 | ERROR   | [ ] Processing form data without nonce verification.
  775 | ERROR   | [ ] Processing form data without nonce verification.
  776 | WARNING | [ ] Processing form data without nonce verification.
  776 | WARNING | [ ] Processing form data without nonce verification.
FILE: /media/k/SSD/htdocs/wptest/wp-content/plugins/directorist/includes/modules/appsero/src/License.php
 233 | ERROR   | [ ] Processing form data without nonce verification.
 234 | ERROR   | [ ] Processing form data without nonce verification.
 715 | WARNING | [ ] Processing form data without nonce verification.
FILE: /media/k/SSD/htdocs/wptest/wp-content/plugins/directorist/includes/modules/appsero/src/Updater.php
FILE: /media/k/SSD/htdocs/wptest/wp-content/plugins/directorist/includes/modules/background-process/wp-async-request.php
FILE: /media/k/SSD/htdocs/wptest/wp-content/plugins/directorist/includes/modules/background-process/wp-background-process.php
FILE: /media/k/SSD/htdocs/wptest/wp-content/plugins/directorist/includes/modules/multi-directory-setup/class-multi-directory-manager.php
  336 | ERROR   | [ ] Processing form data without nonce verification.
  336 | ERROR   | [ ] Processing form data without nonce verification.
  337 | ERROR   | [ ] Processing form data without nonce verification.
  337 | ERROR   | [ ] Processing form data without nonce verification.
  338 | ERROR   | [ ] $_FILES data not unslashed before sanitization. Use wp_unslash() or similar
  338 | ERROR   | [ ] Detected usage of a non-sanitized input variable: $_FILES['directory-import-file']
  458 | ERROR   | [ ] Processing form data without nonce verification.
  472 | ERROR   | [ ] Processing form data without nonce verification.
  472 | ERROR   | [ ] Processing form data without nonce verification.
  473 | ERROR   | [ ] Processing form data without nonce verification.
  476 | ERROR   | [ ] Processing form data without nonce verification.
  479 | ERROR   | [ ] Processing form data without nonce verification.
  480 | ERROR   | [ ] Processing form data without nonce verification.
 4816 | WARNING | [ ] Processing form data without nonce verification.
 4816 | WARNING | [ ] Processing form data without nonce verification.
 4827 | WARNING | [ ] Processing form data without nonce verification.
 4827 | WARNING | [ ] Processing form data without nonce verification.
FILE: /media/k/SSD/htdocs/wptest/wp-content/plugins/directorist/includes/modules/multi-directory-setup/class-multi-directory-migration.php
FILE: /media/k/SSD/htdocs/wptest/wp-content/plugins/directorist/includes/modules/multi-directory-setup/trait-multi-directory-helper.php
FILE: /media/k/SSD/htdocs/wptest/wp-content/plugins/directorist/includes/rest-api/class-datetime.php
FILE: /media/k/SSD/htdocs/wptest/wp-content/plugins/directorist/includes/rest-api/filter-functions.php
FILE: /media/k/SSD/htdocs/wptest/wp-content/plugins/directorist/includes/rest-api/functions.php
FILE: /media/k/SSD/htdocs/wptest/wp-content/plugins/directorist/includes/rest-api/init.php
FILE: /media/k/SSD/htdocs/wptest/wp-content/plugins/directorist/includes/rest-api/Version1/class-abstract-controller.php
FILE: /media/k/SSD/htdocs/wptest/wp-content/plugins/directorist/includes/rest-api/Version1/class-abstract-posts-controller.php
FILE: /media/k/SSD/htdocs/wptest/wp-content/plugins/directorist/includes/rest-api/Version1/class-abstract-terms-controller.php
FILE: /media/k/SSD/htdocs/wptest/wp-content/plugins/directorist/includes/rest-api/Version1/class-builder-controller.php
FILE: /media/k/SSD/htdocs/wptest/wp-content/plugins/directorist/includes/rest-api/Version1/class-categories-controller.php
FILE: /media/k/SSD/htdocs/wptest/wp-content/plugins/directorist/includes/rest-api/Version1/class-directories-controller.php
FILE: /media/k/SSD/htdocs/wptest/wp-content/plugins/directorist/includes/rest-api/Version1/class-listing-reviews-controller.php
FILE: /media/k/SSD/htdocs/wptest/wp-content/plugins/directorist/includes/rest-api/Version1/class-listings-actions-controller.php
FILE: /media/k/SSD/htdocs/wptest/wp-content/plugins/directorist/includes/rest-api/Version1/class-listings-controller.php
FILE: /media/k/SSD/htdocs/wptest/wp-content/plugins/directorist/includes/rest-api/Version1/class-locations-controller.php
FILE: /media/k/SSD/htdocs/wptest/wp-content/plugins/directorist/includes/rest-api/Version1/class-users-account-controller.php
FILE: /media/k/SSD/htdocs/wptest/wp-content/plugins/directorist/includes/rest-api/Version1/class-users-controller.php
FILE: /media/k/SSD/htdocs/wptest/wp-content/plugins/directorist/includes/rest-api/Version1/class-users-favorites-controller.php
FILE: /media/k/SSD/htdocs/wptest/wp-content/plugins/directorist/includes/review/class-admin.php
  89 | WARNING | [ ] Processing form data without nonce verification.
  89 | WARNING | [ ] Processing form data without nonce verification.
FILE: /media/k/SSD/htdocs/wptest/wp-content/plugins/directorist/includes/review/class-bc-review-rating.php
FILE: /media/k/SSD/htdocs/wptest/wp-content/plugins/directorist/includes/review/class-builder-screen.php
FILE: /media/k/SSD/htdocs/wptest/wp-content/plugins/directorist/includes/review/class-builder.php
FILE: /media/k/SSD/htdocs/wptest/wp-content/plugins/directorist/includes/review/class-comment-form-processor.php
  28 | ERROR   | [ ] Processing form data without nonce verification.
  29 | ERROR   | [ ] Processing form data without nonce verification.
FILE: /media/k/SSD/htdocs/wptest/wp-content/plugins/directorist/inclu [...]

2022-07-24 08:34 UTC, kowsar89 commented
Ref:
https://github.com/WordPress/WordPress-Coding-Standards/wiki/Fixing-errors-for-input-data
https://github.com/WordPress/WordPress-Coding-Standards/wiki/Sanitizing-array-input-data
https://github.com/WordPress/WordPress-Coding-Standards/wiki/Escaping-a-WP_Error-object

2022-07-26 03:00 UTC, kowsar89 requested changes
phpcs issue found

2022-07-26 09:27 UTC, kowsar89 requested changes
phpcs issue found

2022-07-26 09:27 UTC, kowsar89 commented on includes/asset-loader/localized_data.php
> +		$miles = ! empty( $_GET['miles'] ) ? absint( $_GET['miles'] ) : 0;
improvements should go into different PR, only security fixes here

2022-07-31 04:03 UTC, vairafiq approved these changes
Looks good

2022-07-31 04:08 UTC, vairafiq requested changes
Review broke in single listing 
![image](https://user-images.githubusercontent.com/36886362/182009615-d8b69555-2501-440d-bcdb-92ae64cbae71.png)

2022-08-01 12:25 UTC, vairafiq commented
https://www.loom.com/share/7f0bbb8b1ddb497eb97632fe92e352b8

2022-08-02 06:31 UTC, vairafiq approved these changes
Tested, works fine

2022-08-02 06:44 UTC, kowsar89 approved these changes
phpcs ok

2022-08-02 06:47 UTC, kowsar89 requested changes
PHP error found
```
[02-Aug-2022 06:46:52 UTC] PHP Parse error:  syntax error, unexpected ')' in /media/k/SSD/xampp/htdocs/wpwax/directorist/wp-content/plugins/directorist/includes/helper-functions.php on line 9009
[02-Aug-2022 06:46:52 UTC] PHP Fatal error:  Exception thrown without a stack frame in Unknown on line 0
[02-Aug-2022 06:46:54 UTC] PHP Parse error:  syntax error, unexpected ')' in /media/k/SSD/xampp/htdocs/wpwax/directorist/wp-content/plugins/directorist/includes/helper-functions.php on line 9009
[02-Aug-2022 06:46:54 UTC] PHP Fatal error:  Exception thrown without a stack frame in Unknown on line 0
[02-Aug-2022 06:47:51 UTC] PHP Parse error:  syntax error, unexpected ')' in /media/k/SSD/xampp/htdocs/wpwax/directorist/wp-content/plugins/directorist/includes/helper-functions.php on line 9009
[02-Aug-2022 06:47:51 UTC] PHP Fatal error:  Exception thrown without a stack frame in Unknown on line 0
[02-Aug-2022 06:47:54 UTC] PHP Parse error:  syntax error, unexpected ')' in /media/k/SSD/xampp/htdocs/wpwax/directorist/wp-content/plugins/directorist/includes/helper-functions.php on line 9009
[02-Aug-2022 06:47:54 UTC] PHP Fatal error:  Exception thrown without a stack frame in Unknown on line 0
```

2022-08-02 08:45 UTC, kowsar89 approved these changes

2022-08-02 08:54 UTC, obiPlabon approved these changes
ok

2022-08-02 08:55 UTC, merged