fix missing required attributes
sovware/directorist pull request #1178
Opened 2022-09-07 08:46 UTC by M4hd1BD

2022-10-11 03:44 UTC, kowsar89 requested changes

2022-10-11 03:44 UTC, kowsar89 commented on templates/account/registration.php
> +								<input id="password" class="directorist-form-element" type="password" name="password" value="" <?php
Keep it in single line, like before

2022-10-11 03:44 UTC, kowsar89 commented on templates/account/registration.php
> +								<input id="listing_t" type="checkbox" name="t_c_check" <?php echo( ( isset( $t_c_check ) && 'on' === $t_c_check ) ? 'checked="checked"' : '' ); ?> required>
doesn't work

2022-10-11 03:44 UTC, kowsar89 commented on templates/account/registration.php
> +								<input id="privacy_policy" type="checkbox" name="privacy_policy" <?php echo( ( isset( $privacy_policy ) && 'on' === $privacy_policy ) ? 'checked="checked"' : '' ); ?> required>
doesn't work

2022-10-11 03:44 UTC, kowsar89 commented on templates/account/registration.php
> +							<input id="fname" class="directorist-form-element" type="text" name="fname" value="<?php echo isset( $_REQUEST['fname']) ? esc_attr( sanitize_text_field( wp_unslash( $_REQUEST['fname'] ) ) ) :
Keep it in single line, like before

2022-10-11 03:44 UTC, kowsar89 commented on templates/account/registration.php
> +							<input class="directorist-form-element" id="lname" type="text" name="lname" value="<?php echo isset( $_REQUEST['lname']) ? esc_attr( sanitize_text_field( wp_unslash( $_REQUEST['lname'] ) ) ) :
Keep it in single line, like before

2022-10-11 03:44 UTC, kowsar89 commented on templates/account/registration.php
> +								<input id="website" class="directorist-form-element" type="text" name="website" value="<?php echo isset( $_REQUEST['website']) ? esc_url( sanitize_text_field( wp_unslash( $_REQUEST['website']
Keep it in single line, like before

2022-10-11 03:44 UTC, kowsar89 commented on templates/account/registration.php
> +							<textarea id="bio" class="directorist-form-element" name="bio" rows="10" <?php
Keep it in single line, like before

2022-10-11 12:26 UTC, M4hd1BD commented on templates/account/registration.php
> +								<input id="password" class="directorist-form-element" type="password" name="password" value="" <?php
Done

2022-10-11 12:34 UTC, M4hd1BD commented on templates/account/registration.php
> +								<input id="listing_t" type="checkbox" name="t_c_check" <?php echo( ( isset( $t_c_check ) && 'on' === $t_c_check ) ? 'checked="checked"' : '' ); ?> required>
Got rid of this. The Checkbox is custom here, this one isn't focusable, need JS to throw error here.

2022-10-11 12:35 UTC, M4hd1BD commented on templates/account/registration.php
> +								<input id="privacy_policy" type="checkbox" name="privacy_policy" <?php echo( ( isset( $privacy_policy ) && 'on' === $privacy_policy ) ? 'checked="checked"' : '' ); ?> required>
Got rid of this. The Checkbox is custom here, this one isn't focusable, need JS to throw error here.

2022-10-11 12:36 UTC, M4hd1BD commented on templates/account/registration.php
> +							<input id="fname" class="directorist-form-element" type="text" name="fname" value="<?php echo isset( $_REQUEST['fname']) ? esc_attr( sanitize_text_field( wp_unslash( $_REQUEST['fname'] ) ) ) :
Done,

2022-10-11 12:37 UTC, M4hd1BD commented on templates/account/registration.php
> +								<input id="website" class="directorist-form-element" type="text" name="website" value="<?php echo isset( $_REQUEST['website']) ? esc_url( sanitize_text_field( wp_unslash( $_REQUEST['website']
Done.

2022-10-11 12:39 UTC, M4hd1BD commented on templates/account/registration.php
> +							<textarea id="bio" class="directorist-form-element" name="bio" rows="10" <?php
Done.

2022-10-12 01:46 UTC, kowsar89 requested changes

2022-10-12 01:46 UTC, kowsar89 commented on templates/account/registration.php
> +							<textarea id="bio" class="directorist-form-element" name="bio" rows="10" <?php echo ( ! empty( $require_bio ) ? 'required' : '' ); ?>> <?php echo isset( $_REQUEST['bio']) ? esc_textarea( sanit
'required' doesn't work

2022-10-13 08:41 UTC, M4hd1BD commented on templates/account/registration.php
> +							<textarea id="bio" class="directorist-form-element" name="bio" rows="10" <?php echo ( ! empty( $require_bio ) ? 'required' : '' ); ?>> <?php echo isset( $_REQUEST['bio']) ? esc_textarea( sanit
Fixed.

2022-10-16 02:18 UTC, kowsar89 approved these changes
Looks good

2022-10-16 02:18 UTC, merged