fixed broken layout for popular and simialr listing category
sovware/directorist pull request #1197
Opened 2022-09-18 06:26 UTC by M4hd1BD

2022-11-01 05:16 UTC, kowsar89 requested changes
php notice http://prntscr.com/hCyem8xkGwfn

2022-11-01 05:16 UTC, kowsar89 commented on templates/widgets/featured-listing.php
> +if (!defined('ABSPATH')) exit;
Unnecessary space changes like this in all php files

2022-11-02 05:27 UTC, M4hd1BD commented on templates/widgets/featured-listing.php
> +if (!defined('ABSPATH')) exit;
Fixed.

2022-11-02 05:53 UTC, kowsar89 requested changes
1. Fix php notice http://prntscr.com/hCyem8xkGwfn
2. Use correct node/npm version when building: http://prntscr.com/Wru19-JzxcAJ
3. Update template version number
4. Sync with alpha

2022-11-02 06:48 UTC, kowsar89 requested changes
don't change icon http://prntscr.com/s-n52gs09lxN

2022-11-03 03:10 UTC, kowsar89 requested changes
Few changes: http://prntscr.com/U_fjiOttBMj3

2022-11-06 01:25 UTC, M4hd1BD commented
> Few changes: http://prntscr.com/U_fjiOttBMj3

Adjusted.

2022-11-06 07:30 UTC, devShamim requested changes
need to test with different themes
https://prnt.sc/Py1TyBoPyV_s

2022-11-06 09:31 UTC, M4hd1BD commented
> need to test with different themes https://prnt.sc/Py1TyBoPyV_s

Improved.

2022-11-07 05:15 UTC, devShamim submitted a review, later dismissed
Looks good!

2022-11-07 05:57 UTC, kowsar89 requested changes
Few style adjustment: http://prntscr.com/tYz0ZmKwm7Sw

2022-11-08 02:40 UTC, kowsar89 requested changes
Theme: Twenty Twenty-Three
Style broken: http://prntscr.com/ULsYd4C3aVzT

2022-11-09 06:22 UTC, kowsar89 approved these changes

2022-11-09 06:22 UTC, merged