fix an issue with wrong operator getting assigned if there is multipl…
sovware/directorist pull request #1239
Opened 2022-10-25 14:30 UTC by M4hd1BD

…e custom fields

2022-11-01 04:49 UTC, kowsar89 requested changes

2022-11-01 04:49 UTC, kowsar89 commented on includes/model/Listings.php
> +					$field_type = preg_replace('/([!^0-9])|(-)/', '', $field_type);
1. Use inline comment explaining what this regular expression does
2. Follow PHP coding standards for space usage: https://developer.wordpress.org/coding-standards/wordpress-coding-standards/php/#space-usage

2022-11-02 05:24 UTC, M4hd1BD commented on includes/model/Listings.php
> +					$field_type = preg_replace('/([!^0-9])|(-)/', '', $field_type);
Done

2022-11-02 05:44 UTC, kowsar89 approved these changes

2022-11-02 05:46 UTC, merged