Js/rearrange
sovware/directorist pull request #1279
Opened 2022-11-27 05:27 UTC by devShamim

## PR Type

- [x] Bugfix

## linked issue
Fixes #1268

2022-11-28 07:02 UTC, kowsar89 requested changes
behavior changed

2022-11-29 03:48 UTC, kowsar89 requested changes
Issue isn't fixed in onelisting theme

2022-11-29 05:04 UTC, kowsar89 requested changes

2022-11-29 05:04 UTC, kowsar89 commented on assets/src/js/public/components/login.js
> +            throw {message : directorist.login_alert_message};
console error: http://prntscr.com/rmJPO0ecepid

2022-11-29 05:04 UTC, kowsar89 commented on assets/src/js/public/components/login.js
> +            $('.directorist-report-abuse-modal').length ? $('.directorist-report-abuse-modal').css('display', 'none') : '';
is this really required?

2022-11-29 05:07 UTC, devShamim commented on assets/src/js/public/components/login.js
> +            $('.directorist-report-abuse-modal').length ? $('.directorist-report-abuse-modal').css('display', 'none') : '';
yes, it's required

2022-11-29 05:07 UTC, devShamim commented on assets/src/js/public/components/login.js
> +            $('.directorist-report-abuse-modal').length ? $('.directorist-report-abuse-modal').css('display', 'none') : '';
> is this really required?

yes, it's required

2022-11-29 05:12 UTC, devShamim commented on assets/src/js/public/components/login.js
> +            throw {message : directorist.login_alert_message};
> console error: http://prntscr.com/rmJPO0ecepid

I had to throw an error to stop the event bubbling since stopPropagation can't use here.

2022-11-29 06:19 UTC, closed without merging