Fix/announcement issues
sovware/directorist pull request #1363
Opened 2023-02-15 07:00 UTC by syedgalib

## PR Type
What kind of change does this PR introduce?

- [ x] Bugfix
- [ ] Security fix
- [ ] Improvement
- [ ] New Feature
- [ ] Refactoring (no functional changes, no api changes)
- [ ] Build related changes
- [ ] Text changes
- [ ] Other... Please describe:

## Description
How to reproduce the issue or how to test the changes

1.
2.
3.

## Any linked issues
Fixes #

## Checklist

- [ ] My code follows the [WordPress coding standards](https://make.wordpress.org/core/handbook/best-practices/coding-standards/)

2023-02-15 08:42 UTC, obiPlabon approved these changes

2023-02-15 08:42 UTC, obiPlabon commented on includes/model/ListingDashboard.php
> +			$recepents = ! empty( $recepents ) ? explode( ',', $recepents ) : [];
Fix typo. correct: recipients

2023-02-15 08:42 UTC, obiPlabon requested changes
Fix typo

2023-02-19 03:44 UTC, vairafiq reviewed
Don't need to merge it to the core, this feature will be removed from the core and will be live as a separate free extension. Also, it requires migration.

2023-11-16 07:53 UTC, closed without merging