fixed directory builder widget label issue
sovware/directorist pull request #1397
Opened 2023-03-08 06:23 UTC by syedgalib

## PR Type
What kind of change does this PR introduce?

- [x] Bugfix
- [ ] Security fix
- [ ] Improvement
- [ ] New Feature
- [ ] Refactoring (no functional changes, no api changes)
- [ ] Build related changes
- [ ] Text changes
- [ ] Other... Please describe:

## Description
How to reproduce the issue or how to test the changes

1.
2.
3.

## Any linked issues
Fixes #

## Checklist

- [ ] My code follows the [WordPress coding standards](https://make.wordpress.org/core/handbook/best-practices/coding-standards/)

2023-03-08 06:56 UTC, obiPlabon requested changes

2023-03-08 06:56 UTC, obiPlabon commented on assets/src/js/admin/vue/modules/form-fields/Card_Builder_Listing_Header_Field.vue
> +      if (
How about https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Operators/Optional_chaining

`widget?.options?.fields?.label?.value?.length && widget?.options?.fields?.type === 'text'`

2023-03-08 07:05 UTC, syedgalib commented on assets/src/js/admin/vue/modules/form-fields/Card_Builder_Listing_Header_Field.vue
> +      if (
Sure

2023-03-09 05:29 UTC, obiPlabon approved these changes
Maybe ok

2023-03-09 05:29 UTC, merged