Fix translation error
sovware/directorist pull request #1575
Opened 2023-08-24 03:57 UTC by HeyMehedi

## PR Type
What kind of change does this PR introduce?

- [x] Bugfix
- [ ] Security fix
- [x] Improvement
- [ ] New Feature
- [x] Refactoring (no functional changes, no api changes)
- [ ] Build related changes
- [ ] Text changes
- [ ] Other... Please describe:

## Checklist

- [x] My code follows the [WordPress coding standards](https://make.wordpress.org/core/handbook/best-practices/coding-standards/)

2023-08-24 08:53 UTC, obiPlabon requested changes

2023-08-24 08:53 UTC, obiPlabon commented on templates/listing-form/fields/tag.php
> +	<select name="<?php echo esc_attr( $data['field_key'] ); ?>" class="directorist-form-element" id="at_biz_dir-tags" data-selected-id="<?php echo esc_attr_( $current_ids_as_string ) ?>" data-selected-
`esc_attr_` @HeyMehedi  please fix it. and run it on your machine before sending any PR.

2023-08-27 03:48 UTC, HeyMehedi commented on templates/listing-form/fields/tag.php
> +	<select name="<?php echo esc_attr( $data['field_key'] ); ?>" class="directorist-form-element" id="at_biz_dir-tags" data-selected-id="<?php echo esc_attr_( $current_ids_as_string ) ?>" data-selected-
Thanks for the correction. Indeed I will check on my machine before sending any PR.

2023-10-12 08:57 UTC, vairafiq approved these changes

2023-10-12 09:08 UTC, obiPlabon approved these changes
Looks good

2023-10-12 09:08 UTC, merged