Searrch Form Style - Improved
sovware/directorist pull request #1662
Opened 2023-11-22 06:44 UTC by iamibrahimriaz

## PR Type
What kind of change does this PR introduce?

- [ ] Bugfix
- [ ] Security fix
- [x] Improvement
- [ ] New Feature
- [ ] Refactoring (no functional changes, no api changes)
- [ ] Build related changes
- [ ] Text changes
- [ ] Other... Please describe:

## Description
How to reproduce the issue or how to test the changes
Issue was:
<img width="525" alt="image" src="https://github.com/sovware/directorist/assets/99108560/af8593d1-0ce2-4012-81b3-bc522ced8f9c">
<img width="535" alt="image" src="https://github.com/sovware/directorist/assets/99108560/336698c1-84bb-4227-8295-2a48505ccea7">

Updated Style:
https://www.loom.com/share/52f1cfdcaed1404f9dc55b9f238756c4

## Checklist

- [x] My code follows the [WordPress coding standards](https://make.wordpress.org/core/handbook/best-practices/coding-standards/)

2023-12-21 07:23 UTC, devShamim requested changes

2023-12-24 06:22 UTC, devShamim requested changes

2023-12-24 06:22 UTC, devShamim commented on templates/single/section-related_listings.php
> +<section class="directorist-related <?php echo esc_attr( $class );?>" <?php $listing->section_id( $id ); ?>>
'direcotirst-related' - what?

2023-12-25 09:32 UTC, iamibrahimriaz commented on templates/single/section-related_listings.php
> +<section class="directorist-related <?php echo esc_attr( $class );?>" <?php $listing->section_id( $id ); ?>>
Fixed

2023-12-25 09:54 UTC, iamibrahimriaz commented on templates/archive/advance-search-form.php
>  		<div class="directorist-advanced-filter__top">
Fixed

2023-12-25 10:25 UTC, iamibrahimriaz commented on templates/archive/loop-grid.php
>  	<figure class="directorist-listing-single__thumb">
Fixed

2023-12-25 10:50 UTC, iamibrahimriaz commented on templates/archive/fields/listings_location.php
> +    <span class="directorist-listing-single__info__list__label">
Fixed

2023-12-25 10:50 UTC, iamibrahimriaz commented on templates/archive/fields/phone2.php
> +<li class="directorist-listing-card-phone2"><?php directorist_icon( $icon ); ?><span class="directorist-listing-single__info__list__label"><?php $listings->print_label( $label ); ?></span><a href="<?
Fixed

2023-12-31 05:30 UTC, merged