Improve/dashboard
sovware/directorist pull request #1677
Opened 2023-12-28 12:45 UTC by Armanul46

## PR Type
What kind of change does this PR introduce?

- [ ] Bugfix
- [ ] Security fix
- [ ] Improvement
- [ ] New Feature
- [ ] Refactoring (no functional changes, no api changes)
- [ ] Build related changes
- [ ] Text changes
- [ ] Other... Please describe:

1. Merge dashboard, login , registration form page
2. ajax registration form
3. remove login & registration page settings
4. Migration system for old user

## Description
How to reproduce the issue or how to test the changes

1.
2.
3.

## Any linked issues
Fixes #

## Checklist

- [ ] My code follows the [WordPress coding standards](https://make.wordpress.org/core/handbook/best-practices/coding-standards/)

2023-12-31 06:15 UTC, vairafiq commented
- Notice is not showing from my main workspace (checking out from alpha)
- When shows in another installation, it is missing on Settings and Builder screen https://prnt.sc/NF0M9p2rG1y1
- When updating the database, it redirects to builder screen and no confirmation (it shouldn't redirect)
- After completing the registration, it redirects the the same page and showing login screen without any confirmation notice https://prnt.sc/Jp5BQY0F5kIS
- When email verification is enabled, successful registration is redirects to the legacy login page https://prnt.sc/W6iMqjzYgu2G

2024-01-02 05:45 UTC, vairafiq commented
- After updating it redirects to the previous page and the page regardless of the confirmation notice https://prnt.sc/EVkJxfm_hwVq
- Remove placeholder from registration and login pages https://prnt.sc/dRiDlouI0Mq3

2024-02-14 03:20 UTC, obiPlabon requested changes

2024-02-14 03:20 UTC, obiPlabon commented on assets/src/js/public/components/register-form.js
> +        var data = {
Better use FormData instead of selecting each field separately

2024-02-14 03:20 UTC, obiPlabon commented on includes/classes/class-updater-notice.php
> +			add_query_arg( 'do_update_directorist', 'true', get_permalink() ),
Why `get_permalink()` is used here?

2024-02-14 03:20 UTC, obiPlabon commented on includes/classes/class-user.php
> +					wp_send_json( $response );
We can use `wp_send_json_error()` to send error and `wp_send_json_success()` for success!

2024-02-27 09:03 UTC, Armanul46 commented on includes/classes/class-updater-notice.php
> +			add_query_arg( 'do_update_directorist', 'true', get_permalink() ),
Because after migration, it was forcefully redirecting to the settings page. Now, it redirects to the same page.

2024-03-03 05:13 UTC, iamibrahimriaz commented
> * Login drop shadow cropped and link invisible due to color issue - https://prnt.sc/Oye6-3eaYFQB
> * Registration issues - https://prnt.sc/ltsUqDVJiQG6 (same as login)
> * Inconsistent notice area (inside the box is better) - https://prnt.sc/s6mVslGf5IDZ https://prnt.sc/u8XjfsIweUbB
> * Resend confirmation redirects to old login page - https://prnt.sc/4sobXggysIlw https://prnt.sc/UeMX-Z9oGpaS
> * Password reset form style doesn't match with others - https://prnt.sc/76vTmlvyKg1F

Style Issue - Fixed

2024-08-04 05:53 UTC, vairafiq approved these changes
All good, thank you @Armanul46

2024-08-04 06:07 UTC, obiPlabon approved these changes
Approved by @vairafiq

2024-08-04 06:07 UTC, merged