fixed checkbox Searching issue
sovware/directorist pull request #218
Opened 2021-05-05 05:53 UTC by Armanul46

2021-05-05 09:14 UTC, vairafiq reviewed
Pass

2021-05-05 10:02 UTC, kowsar89 commented
@Armanul46 in alpha file path changed, please check and update again

2021-05-05 10:03 UTC, kowsar89 requested changes
@Armanul46 in alpha file path changed, please check and update again

2021-05-06 09:03 UTC, vairafiq approved these changes

2021-05-06 10:52 UTC, kowsar89 approved these changes

2021-05-06 10:54 UTC, merged