added style tab
sovware/directorist pull request #264
Opened 2021-05-24 06:13 UTC by HeyMehedi

2021-06-13 08:26 UTC, kowsar89 requested changes
change alignment

2021-06-16 06:44 UTC, kowsar89 requested changes
default alignment isssue

2021-06-17 03:06 UTC, kowsar89 approved these changes
Tested, now works fine

2021-06-17 04:13 UTC, vairafiq reviewed
Looks good

2021-06-17 04:13 UTC, merged