fixed search listing shortcode atts not working after ajax load
sovware/directorist pull request #480
Opened 2021-09-29 07:58 UTC by syedgalib

2021-09-29 09:13 UTC, vairafiq approved these changes
Tested. Works fine

2021-09-29 10:30 UTC, kowsar89 requested changes

2021-09-29 10:30 UTC, kowsar89 commented on includes/classes/class-shortcode.php
> +		// var_dump(  $atts );
remove var_dump

2021-09-30 03:35 UTC, kowsar89 requested changes
Doesn't work if shortcode is used multiple times in a page.
![image](https://user-images.githubusercontent.com/6196149/135382846-a1248d76-4db5-47cc-ad22-9937e08b3887.png)

2021-09-30 05:04 UTC, syedgalib commented
fixed

2021-09-30 08:46 UTC, merged