Fixed: all listing page dropdown toggle issue
sovware/directorist pull request #544
Opened 2021-11-07 07:46 UTC by shamimsaj

2021-11-16 06:48 UTC, kowsar89 requested changes
Need more details(eg clickup link) about the issue

2021-11-17 04:47 UTC, vairafiq approved these changes

2021-11-17 04:58 UTC, vairafiq commented
![image](https://user-images.githubusercontent.com/36886362/142136530-34404e5e-1027-4c72-814f-4215cd305279.png)
Fixed the issue

2021-11-17 06:17 UTC, kowsar89 approved these changes
pass

2021-11-17 06:20 UTC, merged