Fix security issues
sovware/directorist pull request #571
Opened 2021-11-16 09:33 UTC by obiPlabon

2021-11-16 09:55 UTC, kowsar89 requested changes
template version not updated

2021-11-16 10:08 UTC, kowsar89 requested changes

2021-11-16 10:08 UTC, kowsar89 commented on includes/classes/class-user.php
> + * User registration and acess management related functionalities can be found in this class.
Typo

2021-11-17 10:19 UTC, obiPlabon commented on includes/classes/class-user.php
> + * User registration and acess management related functionalities can be found in this class.
Fixed

2021-11-17 11:31 UTC, kowsar89 approved these changes
Works fine

2021-11-17 13:43 UTC, vairafiq approved these changes

2021-11-17 13:43 UTC, merged