Fix/add listing shortcode parameter
sovware/directorist pull request #594
Opened 2021-11-29 09:06 UTC by Armanul46

https://app.clickup.com/t/1tth26k

2021-12-05 04:34 UTC, kowsar89 requested changes
If default listing type is different than current listing type, it saves things as default listing type

2021-12-05 06:57 UTC, obiPlabon commented
The form is displayed properly when the slug is used and a directory exists with that slug. Fatal error otherwise

```
Fatal error: Uncaught Error: Class 'Helper' not found in /Users/macbookpro/Local Sites/testdirectorist/app/public/wp-content/plugins/directorist/templates/listing-form/add-listing-notype.php on line 12 ( ! ) Error: Class 'Helper' not found in /Users/macbookpro/Local Sites/testdirectorist/app/public/wp-content/plugins/directorist/templates/listing-form/add-listing-notype.php on line 12 Call Stack #TimeMemoryFunctionLocation 10.0003409184{main}( ).../index.php:0 20.0003409456require( '/Users/macbookpro/Local Sites/testdirectorist/app/public/wp-blog-header.php' ).../index.php:17 30.12885096736require_once( '/Users/macbookpro/Local Sites/testdirectorist/app/public/wp-includes/template-loader.php' ).../wp-blog-header.php:19 40.13675134776include( '/Users/macbookpro/Local Sites/testdirectorist/app/public/wp-content/themes/twentytwentyone/page.php' ).../template-loader.php:106 50.21425568712get_template_part( ).../page.php:17 60.21435569232locate_template( ).../general-template.php:204 70.21435569392load_template( ).../template.php:716 80.21435569776require( '/Users/macbookpro/Local Sites/testdirectorist/app/public/wp-content/themes/twentytwentyone/template-parts/content/content-page.php' ).../template.php:772 90.21565570608the_content( ).../content-page.php:29 100.21675570608apply_filters( ).../post-template.php:253 110.21675571008WP_Hook->apply_filters( ).../plugin.php:189 120.21725639704do_shortcode( ).../class-wp-hook.php:303 130.21725643960preg_replace_callback ( ).../shortcodes.php:228 140.21725644640do_shortcode_tag( ).../shortcodes.php:228 150.21735645112Directorist\ATBDP_Shortcode->add_listing( ).../shortcodes.php:356 160.21855646480Directorist\Directorist_Listing_Form->render_shortcode( ).../class-shortcode.php:235 170.22165659192Directorist\Helper::get_template_contents( ).../ListingForm.php:865 180.22165675704Directorist\Helper::get_template( ).../trait-uri-helper.php:14 190.22175676144include( '/Users/macbookpro/Local Sites/testdirectorist/app/public/wp-content/plugins/directorist/templates/listing-form/add-listing-notype.php' ).../trait-uri-helper.php:73
```

2021-12-05 06:58 UTC, kowsar89 submitted a review, later dismissed
works fine now

2021-12-05 07:02 UTC, obiPlabon requested changes
Please fix the fatal error issue.

2021-12-05 07:11 UTC, Armanul46 commented
Fixed the undefined class issue

2021-12-05 07:15 UTC, kowsar89 approved these changes

2021-12-06 06:44 UTC, obiPlabon commented
@Armanul46 `directorist-alert directorist-alert-info` please use these class and style the error text.

2021-12-06 07:00 UTC, obiPlabon approved these changes
Looks good

2021-12-06 08:09 UTC, kowsar89 requested changes

2021-12-06 08:09 UTC, kowsar89 commented on includes/model/ListingForm.php
> +						$args['error_notice'] = sprintf( __('Please add a directory type first %s', 'directorist' ), '<span><a href="'. admin_url() .'/edit.php?post_type=at_biz_dir&page=atbdp-directory-types">Add Now<
1. Why extra <span>?
2. Double slash in link

2021-12-06 08:09 UTC, kowsar89 commented on includes/model/ListingForm.php
> +					$args['error_notice'] = __('Notice: your given directory type is not valid. Please use a valid directory type', 'directorist');
'your' - should be capital letter

2021-12-06 09:00 UTC, kowsar89 approved these changes
seems ok

2021-12-06 09:06 UTC, merged