Improve/select option fields
sovware/directorist pull request #601
Opened 2021-12-05 08:31 UTC by syedgalib

2021-12-05 15:35 UTC, obiPlabon commented
`directorist_on_mount` - conventionally **mount** is not suitable for WordPress, instead we can simply use `directorist_installed`. That's easy to remember even for a novice WordPress dev, `on_mount` or `mount` is good for someone with React or Vue or JS experience.

2021-12-05 16:41 UTC, obiPlabon requested changes

2021-12-05 16:41 UTC, obiPlabon commented on includes/classes/class-script-helper.php
> +            'home_url'                    => home_url(),
Instead of using the `home_url()` we should use `rest_url()`, as the rest URL can be modified using filter hook.

More details...
https://developer.wordpress.org/reference/functions/rest_url/
https://developer.wordpress.org/reference/functions/rest_get_url_prefix/

2021-12-05 16:41 UTC, obiPlabon commented on includes/helper-functions.php
> +function directorist_is_new_user() {
The function name is kinda misleading, maybe we can use `directorist_is_listings_empty()`? Also, we can optimize queries by disabling caching and pagination to avoid worst case.
```
'no_found_rows' => true 
'cache_results' => false
`

2021-12-06 04:14 UTC, kowsar89 approved these changes
Pass. Seach-form seems working though

2021-12-06 07:38 UTC, obiPlabon commented
![image](https://user-images.githubusercontent.com/10244644/144806254-65e9f41a-8651-411c-aba2-1aa28cb5074f.png)
These's an encoding issue...

2021-12-06 09:47 UTC, obiPlabon approved these changes
Looks good

2021-12-06 10:01 UTC, vairafiq approved these changes
pass

2021-12-06 10:04 UTC, kowsar89 approved these changes
pass

2021-12-06 10:05 UTC, merged