Fixed parameter issue of search listing shortcode
sovware/directorist pull request #608
Opened 2021-12-08 08:39 UTC by Armanul46

https://prnt.sc/22a2hqz

2021-12-08 08:43 UTC, vairafiq requested changes
![image](https://user-images.githubusercontent.com/36886362/145176807-a6c14cab-8235-46ac-a0cd-b2fa8390ecad.png)
sometimes it might be empty!

2021-12-21 03:56 UTC, kowsar89 requested changes

2021-12-21 03:56 UTC, kowsar89 commented on includes/helpers/trait-uri-helper.php
> +	public static function is_field_allowed_in_atts( $widget_name, $atts = [] ) {
This file is intended for URL related functions only.
pls move this func into 'Directorist_Listing_Search_Form' class

2021-12-21 04:13 UTC, kowsar89 commented
Discussion summery:
1. Attribute should be like 'filter_category' instead of 'category'
2. Should also work for 'all listings' and 'search result' page
3. After task is completed, update doc

2021-12-21 05:35 UTC, kowsar89 requested changes
Empty space

2021-12-21 05:35 UTC, kowsar89 commented on includes/model/Listings.php
> +				'searchform' => new Directorist_Listing_Search_Form( $this->type, $this->current_listing_type, $this->atts ),
All Liistings atts should not be polluted with Search_Form atts, both are different

2021-12-23 03:37 UTC, kowsar89 requested changes

2021-12-23 03:37 UTC, kowsar89 commented on includes/model/SearchForm.php
> +		if( ! $this->is_field_allowed_in_atts( $field_data['widget_name'], $this->atts ) ) {
why pass $this->atts parameter? since the function is in the same class that value could be retrieved easily without passing parameter

2021-12-23 03:37 UTC, kowsar89 commented on includes/model/Listings.php
> +			$search_field_atts = array_intersect_key( $this->atts, array_flip( preg_grep("/^filter_/", array_keys( $this->atts ) ) ) );
Please make it more readable. eg you can make it into multiple lines, optionally add comments
Ref: https://www.freecodecamp.org/news/long-code-vs-short-code/

2021-12-26 02:51 UTC, merged

2021-12-26 03:52 UTC, kowsar89 commented
Related: https://github.com/sovware/directorist/pull/616