Ajax search
sovware/directorist pull request #725
Opened 2022-02-22 06:30 UTC by Armanul46

please enable "Instance Search" before testing
https://prnt.sc/ctqs5UTQfOef

2022-02-24 06:02 UTC, obiPlabon requested changes
Please update all the references of "instance search, Instance search, ajax search, Ajax search" to "instant search, Instant search". Definitely including CSS class, js function name, PHP class, PHP function, nonce etc. The term must be consistent.

2022-02-27 08:22 UTC, obiPlabon commented
<img width="549" alt="image" src="https://user-images.githubusercontent.com/10244644/155874578-186354ae-23c1-4235-8894-d792f1b5a7c9.png">
Multiple tags are selected but only the last tag is used in the url.

2022-03-01 05:15 UTC, kowsar89 approved these changes
Checked only models and template code changes, looks ok

2022-03-16 03:08 UTC, obiPlabon approved these changes
Search functionality looks good and working as expected.

2022-03-16 04:43 UTC, merged

2022-03-16 04:58 UTC, obiPlabon requested changes

2022-03-16 04:58 UTC, obiPlabon commented on includes/model/Listings.php
> +		public function instant_searching_class() {
```php
/**
 * Displays the class names for the listings wrapper element.
 *
 * @since 7.2.0
 *
 * @param string|string[] $class Space-separated string or array of class names to add to the class list.
 */
public function wrapper_class( $class = '' ) {
	// Separates class names with a single space, collates class names for wrapper tag element.
	echo 'class="' . esc_attr( implode( ' ', $this->get_wrapper_class( $class ) ) ) . '"';
}

/**
 * Retrieves an array of the class names for the listings wrapper element.
 *
 * @since 7.2.0
 *
 * @param string|string[] $class Space-separated string or array of class names to add to the class list.
 * @return string[] Array of class names.
 */
public function get_wrapper_class( $class = '' ) {
	$classes = array(
		'directorist-archive-contents',
	);

	if ( 'yes' === $this->instant_search ) {
		$classes[] = 'directorist-instant-search';
	}

	if ( ! empty( $class ) ) {
		if ( ! is_array( $class ) ) {
			$class = preg_split( '#\s+#', $class );
		}
		$classes = array_merge( $classes, $class );
	} else {
		// Ensure that we always coerce class to being an array.
		$class = array();
	}

	$classes = array_map( 'esc_attr', $classes );

	/**
	 * Filters the list of CSS listings wrapper class names for the wrapper.
	 *
	 * @since 7.2.0
	 *
	 * @param string[] $classes An array of listings wrapper class names.
	 * @param string[] $class   An array of additional class names added to the listings wrapper.
	 * @param object   $this    An instantce of Directorist_Listings
	 */
	$classes = apply_filters( 'directorist_listings_wrapper_class', $classes, $class, $this );

	return array_unique( $classes );
}
```

2022-03-16 04:59 UTC, obiPlabon commented on includes/model/Listings.php
> +		public function instant_searching_class() {
Inspired by https://developer.wordpress.org/reference/functions/body_class/