Widget templating
sovware/directorist pull request #760
Opened 2022-03-13 07:04 UTC by Armanul46

2022-03-13 09:38 UTC, kowsar89 requested changes

2022-03-13 09:38 UTC, kowsar89 commented on templates/widgets/all-locations.php
> +use Directorist\Directorist_Listings;
remove this line from all files if unused

2022-03-13 09:38 UTC, kowsar89 commented on includes/widgets/all-categories.php
> +        $name           = esc_html__( 'Directorist - Categories', 'directorist', 'directorist' );
double textdomain, this issue exists in other files as well

2022-03-13 09:38 UTC, kowsar89 commented on includes/widgets/all-tags.php
> +    public function atbdp_tags_list( $settings ) {
use 'directorist' prefix instead of 'atbdp' in all methods, check other files too

2022-03-13 09:43 UTC, kowsar89 requested changes

2022-03-13 09:43 UTC, kowsar89 commented on directorist-base.php
> +		// register_widget('BD_Popular_Listing_Widget');
remove these comments

2022-03-13 09:43 UTC, kowsar89 commented on includes/model/Listings.php
> +	public static function popular_listings_query( $count = 5 ) {
move this method inside widgets class

2022-03-13 09:45 UTC, kowsar89 commented
Also fix merge conflicts

2022-03-14 02:57 UTC, kowsar89 approved these changes
Code looks good, need front-end check

2022-03-14 03:23 UTC, vairafiq commented
<img width="632" alt="Screen Shot 2022-03-14 at 9 20 14 AM" src="https://user-images.githubusercontent.com/36886362/158099227-8d09f666-d19d-4ee3-9838-2b675351042e.png">

Looks like version as second parameter in docs https://developer.wordpress.org/reference/functions/_deprecated_function/

2022-03-14 03:26 UTC, kowsar89 requested changes

2022-03-14 03:26 UTC, kowsar89 commented on directorist-base.php
> +		_deprecated_function( '7.2.2', 'ATBDP()->show_popular_listing' );
wrong usage of _deprecated_function, https://developer.wordpress.org/reference/functions/_deprecated_function/

2022-03-16 05:15 UTC, vairafiq commented
widget style breaks in theme's default sidebar

Alpha
![Screen Shot 2022-03-16 at 11 13 40 AM](https://user-images.githubusercontent.com/36886362/158521242-125f5901-33dd-4bdc-827f-556975bc547f.png)

Current
![Screen Shot 2022-03-16 at 11 14 52 AM](https://user-images.githubusercontent.com/36886362/158521335-0df76d74-aae1-477d-bd38-69cd78eec83c.png)

2022-03-16 06:38 UTC, merged

2022-03-16 07:14 UTC, vairafiq commented
![Screen Shot 2022-03-16 at 1 11 12 PM](https://user-images.githubusercontent.com/36886362/158536109-0332b57b-194a-48ae-96d0-5bb5e3b9900c.png)
Error in widget screen