introduce a hook to do stuff with each listing after importing them
sovware/directorist pull request #765
Opened 2022-03-14 05:30 UTC by M4hd1BD

2022-03-14 05:54 UTC, obiPlabon requested changes

2022-03-14 05:54 UTC, obiPlabon commented on includes/classes/class-tools.php
> +                    do_action('directorist_after_import_single_listing', $post_id, $post);
Could you please rename it to `directorist_listing_imported`?

```php
/**
 * Fire this event once a listing is successfully imported from CSV.
 *
 * @param int $post_id Listing id.
 * @param array $post  Listing data.
 */
do_action( 'directorist_listing_imported', $post_id, $post );
```

2022-03-14 05:59 UTC, M4hd1BD commented on includes/classes/class-tools.php
> +                    do_action('directorist_after_import_single_listing', $post_id, $post);
adjusted

2022-03-16 09:07 UTC, vairafiq commented
![Screen Shot 2022-03-16 at 3 06 08 PM](https://user-images.githubusercontent.com/36886362/158555024-3d4d800a-d9c9-4e49-88ae-99c1c8244f96.png)

@since is missing in docblock

2022-03-16 09:28 UTC, vairafiq approved these changes
Looks good

2022-03-16 09:37 UTC, merged