Zipcode radius search
sovware/directorist pull request #792
Opened 2022-03-24 03:06 UTC by Armanul46

2022-04-04 05:17 UTC, vairafiq commented
![image](https://user-images.githubusercontent.com/36886362/161478479-158520aa-b706-4c5c-b4d8-8042c743640b.png)

Need to solve conflict

2022-04-04 08:58 UTC, obiPlabon requested changes
@Armanul46 please use CSS classes instead of ids. Use jQuery instead of DOM APIs.

2022-04-04 08:58 UTC, obiPlabon commented on assets/src/js/public/search-form-listing.js
> +    $('body').on("keyup", '.zip-radius-search', function(){
Use debounce mechanism here, otherwise, there'll be lots of unnecessary API calls.
https://davidwalsh.name/javascript-debounce-function

2022-04-04 08:58 UTC, obiPlabon commented on assets/src/js/public/search-form-listing.js
> +                    $('#zip-cityLat').val(lat);
Please use a class selector instead of ID. make sure multiple search form works perfectly on a single page.

2022-04-04 08:58 UTC, obiPlabon commented on assets/src/js/public/search-form-listing.js
> +    document.querySelectorAll(".directorist-search-contents").forEach(function (el) {
Use jQuery instead

2022-04-04 08:58 UTC, obiPlabon commented on includes/modules/multi-directory-setup/class-multi-directory-manager.php
> +                            'radius_search_based_on' => [
Do we have a radio button? Use that if available.

2022-04-10 09:50 UTC, obiPlabon approved these changes
working fine

2022-04-10 09:50 UTC, merged