fixed category field shows all categories
sovware/directorist pull request #865
Opened 2022-04-18 10:24 UTC by syedgalib

2022-06-06 04:19 UTC, vairafiq commented
![image](https://user-images.githubusercontent.com/36886362/172094074-bb15b0ff-5b50-44f4-9587-2f30b961930b.png)

No category when instant search is enabled

2022-06-13 04:16 UTC, vairafiq commented
![Screen Shot 2022-06-13 at 10 15 58 AM](https://user-images.githubusercontent.com/36886362/173278597-7b91421f-e5ff-4436-b353-d94aa84759b6.png)
Still showing all categories when Category Lazy loading is enabled

2022-06-16 05:47 UTC, kowsar89 requested changes

2022-06-16 05:47 UTC, kowsar89 commented on templates/archive/directory-type-nav.php
> +					<a class="directorist-type-nav__link" href="<?php echo esc_url( directorist_get_directory_type_nav_url( $value['term']->slug ) ); ?>" data-listing_type="<?php echo $value['term']->slug; ?>" data
Need proper escaping

2022-06-16 05:47 UTC, kowsar89 commented on includes/model/Listings.php
> +			$atts = $this->atts;
what is the purpose to modify this method?

2022-06-16 06:25 UTC, syedgalib commented on includes/model/Listings.php
> +			$atts = $this->atts;
The Select2 controller of the category field requires directory type ID for its functionality, so extracted the directory type id from its slug and appended to the atts data.

2022-06-16 10:38 UTC, merged