Radius search fix
sovware/directorist pull request #939
Opened 2022-06-16 06:01 UTC by kowsar89

2022-06-16 10:10 UTC, obiPlabon requested changes

2022-06-16 10:10 UTC, obiPlabon commented on includes/model/SearchForm.php
> -	public function range_slider_data( $data ) {
Please do not delete any method without prior notice. We can deprecate first then after 3/4 releases we can hard deprecate or remove that method.

2022-06-19 03:04 UTC, kowsar89 commented on includes/model/SearchForm.php
> -	public function range_slider_data( $data ) {
This method still exists in line 340

2022-06-19 04:13 UTC, obiPlabon commented on includes/model/SearchForm.php
> -	public function range_slider_data( $data ) {
Sorry, my bad.

2022-06-19 05:56 UTC, vairafiq approved these changes
Reviewed

2022-06-19 09:42 UTC, vairafiq commented
Searched radius is not checked in advanced filter

2022-06-21 04:57 UTC, vairafiq commented
Still not working https://www.awesomescreenshot.com/video/9556385?key=cae85b031c32738af28266bd7cb9508b

2022-06-30 04:17 UTC, vairafiq commented
Working perfectly now

2022-06-30 07:08 UTC, obiPlabon approved these changes
Working fine

2022-06-30 07:08 UTC, merged