dashboard modal issue fixed
sovware/directorist pull request #959
Opened 2022-06-26 08:53 UTC by tanjimhasan

2022-06-26 09:17 UTC, kowsar89 commented
### Issue Details
dashboard button
pay now and promote button doens't work 
https://ibb.co/jk803Jm

2022-06-26 09:38 UTC, kowsar89 requested changes

2022-06-26 09:38 UTC, kowsar89 commented on assets/src/js/public/atmodal.js
> +		Author: AazzTech
we don't use "AazzTech" anymore

2022-06-27 02:29 UTC, tanjimhasan commented
Aztech removed

2022-06-27 03:31 UTC, kowsar89 approved these changes
works fine

2022-06-27 03:32 UTC, merged