category select arrow fix
sovware/directorist pull request #976
Opened 2022-06-29 10:08 UTC by tanjimhasan

2022-06-29 11:24 UTC, tanjimhasan commented
https://prnt.sc/fbbFU_WH8qYi
issue fixed

2022-06-30 05:44 UTC, kowsar89 commented on assets/src/js/global/components/select2-custom-control.js
> +            setTimeout( init, 300 );
why settimeout is used? is it a good practice? @tanjimhasan

2022-06-30 07:20 UTC, M4hd1BD reviewed
Need Improvements

2022-07-05 10:17 UTC, kowsar89 requested changes
why package-lock.json is updated? make sure node version is same when building assets

2022-07-05 10:17 UTC, kowsar89 commented
Works fine,  confirmed by Tayar

2022-07-17 10:03 UTC, kowsar89 commented
closed on the favour of https://github.com/sovware/directorist/pull/1000

2022-07-17 10:03 UTC, closed without merging